### ISSUE TITLE
Moving back with incremental content

### ISSUE THREAD

**Issue by jrom** [schacon/showoff#11]
When moving back to a slide with incremental content, should be shown fully loaded, not in its first state. Can use the included example to demo this: if you move back from the last to the first slide, you see nothing.

**Comment by schacon** [comment]
this is the same way keynote works, which is what i'm used to.  i may include separate keybindings for going back but doing incremental content in reverse, which may be more what you're looking for.  if you want to include a patch to make it so that the first time you back up into a inc slide, it shows the full content and the second time it goes to the previous slide, i will pull it in, but i don't really need it enough to do it myself right now.

**Comment by jrom** [comment]
This is what I meant: http://github.com/jrom/showoff/tree/cool_back_steps

Without this, it's really hard to know what slide are you going to when moving backward.

**Comment by schacon** [comment]
merged in
