### ISSUE TITLE
support mathjax

### ISSUE THREAD

**Issue by kashif** [schacon/showoff#61]
would be great to be able to have mathjax support.

**Comment by jfinkels** [comment]
Performed the naive one-line fix for this: added a link to the hosted mathjax script: b4282c3d904785a57a004f02efac0f2833502023

It seems to work with some fiddling (needs some extra backslashes, extra spaces, etc.). I also added an example slide.

https://github.com/jfinkels/showoff/tree/mathjax-support

**Comment by schacon** [comment]
i have a PR for this, but I can't statically link to mathjax hosted in all situations.  you should be able to just put the mathjax js in your repository and showoff will load it in.  why wouldn't that work?  i'll test it.

**Comment by jfinkels** [comment]
I believe it would work fine, I just didn't want to add another
library to be distributed with showoff.

On Sun, Sep 11, 2011 at 12:07 PM, Scott Chacon
reply@reply.github.com
wrote:

**Comment by schacon** [comment]
No, I mean in your presentation repo.
On Sep 11, 2011 9:21 AM, "Jeffrey Finkelstein" <
reply@reply.github.com>
wrote:

**Comment by jfinkels** [comment]
I've checked this out now. It's slightly more complicated since 1) MathJax isn't just a single file that you can just drop in and 2) you must specify a configuration file for MathJax, either as a URL parameter or programmatically in Javascript.

What I've done is this:
1. Download the MathJax distribution into a directory called, for example, `mathjax/` in my presentation repository.
2. Create a `mathjax.js` script in the top level directory of my repository which contains the following code:
   
   ``` javascript
   (function() {
     "use strict";
     var node = document.createElement('script');
     node.setAttribute('type', 'text/javascript');
     node.setAttribute('src', 'file/mathjax/MathJax.js?config=TeX-AMS_HTML');
     document.getElementsByTagName("head")[0].appendChild(node);
   }());
   ```
   
   Note the prefix of "file/", which seems to be the prefix showoff adds to dynamically loaded javascript files, and note also the configuration specified in the URL.

Showoff will now dynamically load `mathjax.js`, which will in turn append a `<script>` child referencing MathJax to the head of the document.

**Comment by goncalossilva** [comment]
Showoff now supports Maruku's math features (which use LaTeX) as an alternative to this. I'm closing it now. Please reopen if you need something from MathJax you can't achieve with Maruku.
